apiVersion: v1
kind: ConfigMap
metadata:
  name: streamlit-configmap
  labels:
    app: streamlit
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
  labels:
    app: streamlit
spec:
  type: NodePort
  ports:
   - port: 8502
  selector:
   app: streamlit
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: streamlit
  labels:
    app: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      volumes:
      - name: volume-cfg
      containers:
      - name: streamlit
        image: custom-image:v04
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 128Mi
        ports:
        - name: http
          containerPort: 8501
          protocol: TCP
        envFrom:
        - configMapRef:
            name: streamlit-configmap
        volumeMounts:
        - name: volume-cfg
          mountPath: /etc/
        livenessProbe:
          httpGet:
            path: /status.php
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /status.php
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 20
        imagePullPolicy: Never
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      initContainers:
      - name: streamlit-init
        image: custom-image:v04
        command: ["ls"]
        imagePullPolicy: Never
